# Playlist-Downloader Configuration File
# This file contains all default settings for the application

spotify:
  client_id: "YOUR CLIENT ID"
  client_secret: "YOUR CLIENT SECRET"
  redirect_url: "YOUR_REDIRECT_URL/callback"
  scope: "playlist-read-private playlist-read-collaborative user-library-read"

download:
  output_directory: "../Playlist Downloads"
  format: "m4a"           # mp3, flac, m4a
  quality: "high"         # low, medium, high
  bitrate: 320           # For MP3 format
  concurrency: 3         # Parallel downloads
  retry_attempts: 3      # Retry failed downloads
  timeout: 300           # 5 minutes timeout per download

audio:
  trim_silence: true     # Remove silence from start/end
  normalize: false       # Audio normalization
  max_duration: 960      # 16 minutes maximum
  min_duration: 30       # 30 seconds minimum
  sample_rate: 44100     # Audio sample rate
  channels: 2            # Stereo audio

ytmusic:
  search_algorithm: "multi_strategy"  # multi_strategy, simple
  max_results: 5                      # Results to analyze per search
  score_threshold: 70                 # Minimum match score (0-100)
  prefer_official: true               # Prefer "Official Audio" tracks
  exclude_live: true                  # Exclude live performances
  exclude_covers: true                # Exclude cover versions
  duration_tolerance: 15              # Seconds tolerance for duration matching


lyrics:
  enabled: true
  download_separate_files: true        # Save .lrc/.txt files
  embed_in_audio: true                # Embed in ID3 tags
  format: "lrc"                       # lrc, txt, both
  primary_source: "genius"            # genius, syncedlyrics
  fallback_sources: ["syncedlyrics"] 
  clean_lyrics: true                  # Remove [Verse], [Chorus] markers
  min_length: 50                      # Skip very short lyrics
  timeout: 30                         # Timeout per search (seconds)
  max_attempts: 3                     # Max retry per source
  
  # API Keys (optional for better rate limits)
  genius_api_key: "YOUR GENIUS API TOKEN"
  
  # Advanced lyrics settings
  similarity_threshold: 0.7           # Title/artist similarity threshold
  exclude_instrumental: true          # Skip instrumental tracks
  include_translations: false         # Include translated lyrics if available

sync:
  auto_sync: false       # Automatic synchronization
  check_interval: 3600   # 1 hour in seconds
  sync_lyrics: true      # Include lyrics in sync operations
  backup_tracklist: true # Backup tracklist.txt before modifications
  detect_moved_tracks: true  # Detect and handle moved tracks

metadata:
  include_album_art: true     # Download and embed album artwork
  include_spotify_metadata: true  # Include Spotify-specific metadata
  preserve_original_tags: false   # Keep existing ID3 tags
  add_comment: true               # Add "Downloaded by Playlist-Downloader" comment
  
  # ID3 tag configuration
  id3_version: "2.4"             # ID3 version to use
  encoding: "utf-8"              # Text encoding
  include_lyrics_in_comment: false  # Include lyrics source in comment

logging:
  level: "INFO"                  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "playlist-dl.log"        # Log file name
  max_size: "10MB"              # Maximum log file size
  backup_count: 3               # Number of backup log files
  console_output: true          # Show logs in console
  colored_output: true          # Use colored console output

network:
  user_agent: "Playlist-Downloader/1.0"
  request_timeout: 30           # HTTP request timeout
  max_retries: 3               # Maximum retry attempts
  retry_delay: 1               # Delay between retries (seconds)
  rate_limit_delay: 1          # Delay between requests (seconds)

security:
  token_storage_path: "~/.playlist-downloader/tokens.json"
  config_directory: "~/.playlist-downloader/"
  encrypt_tokens: false        # Encrypt stored tokens (future feature)

# Feature flags
features:
  experimental_parallel_lyrics: false  # Experimental parallel lyrics download
  smart_retry_algorithm: true          # Use smart retry with exponential backoff
  advanced_audio_analysis: false       # Use librosa for advanced audio analysis
  playlist_backup: true                # Create backup of playlist data

# File naming patterns
naming:
  track_format: "{track:02d} - {artist} - {title}"  # Track file naming pattern
  sanitize_filenames: true                          # Remove invalid characters
  max_filename_length: 200                          # Maximum filename length
  replace_spaces: false                             # Replace spaces with underscores